output   = "pkg/models"
wipe     = true

[psql]
dbname = "parsec"
host = "localhost"
port = 5435
user = "parsec"
pass = "password"
sslmode = "disable"
blacklist = ["schema_migrations", "clustertest_runs", "clustertest_nodes", "clustertest_retrievals", "clustertest_provides"]